"""Publish the v0 placeholder LoRA repo (config + sample data)."""

from __future__ import annotations

import json
from pathlib import Path

from huggingface_hub import HfApi
from rich.console import Console

from apps.api.core.config import get_settings

console = Console()

REPO_ID = "vaatus/agentready-chaos-remediation-lora-v0"
BASE_MODEL = "Qwen/Qwen2.5-7B-Instruct"


_MODEL_CARD = f"""---
license: apache-2.0
base_model: {BASE_MODEL}
tags:
- peft
- lora
- agentic-ai
- owasp
- chaos-engineering
- amd-mi300x
- agentready
library_name: peft
pipeline_tag: text-generation
---

# AgentReady Chaos-Remediation LoRA (v0 placeholder)

LoRA adapter trained on synthetic recovery data harvested from the AgentReady
chaos engineering pipeline. Target failure modes:

- Rate-limit (HTTP 429) backoff/retry policy regressions
- Schema-drift JSON parsing under field renames
- Partial-response stream truncation
- KV-cache eviction mid-conversation
- Authentication expiry mid-session

## Base model

[`{BASE_MODEL}`]({f'https://huggingface.co/{BASE_MODEL}'}) — sponsor partner of the AMD Developer Hackathon.

## Training environment

- **Hardware:** AMD Instinct™ MI300X (192 GB VRAM) via the AMD Developer Cloud
- **Stack:** Unsloth + PEFT + TRL on ROCm 7.2
- **Adapter:** rank 8, α=16, target modules `[q_proj, v_proj]`, dropout 0.05
- **Synthetic data:** generated by handing chaos failure traces back to the
  Judge LLM (also Qwen 2.5 7B) and asking for recovery completions.

## Status

This is the **v0 placeholder repo**. The released configuration matches
`adapter_config.json`, but the safetensors checkpoint is trained off-site
and pushed in a follow-up release. Subscribe / watch for v1.0.

The training pipeline lives at
[`scripts/train_chaos_lora.py`](https://github.com/vaatus/agentready/blob/main/scripts/train_chaos_lora.py)
in the AgentReady repo.

## License

Apache-2.0 — same as the base Qwen2.5 model.

## Citation

If you reference this work, cite [AgentReady](https://github.com/vaatus/agentready)
(public benchmark for AI agents under OWASP ASI-2026).
"""


_ADAPTER_CONFIG = {
    "auto_mapping": None,
    "base_model_name_or_path": BASE_MODEL,
    "bias": "none",
    "fan_in_fan_out": False,
    "inference_mode": True,
    "init_lora_weights": True,
    "layers_pattern": None,
    "layers_to_transform": None,
    "lora_alpha": 16,
    "lora_dropout": 0.05,
    "modules_to_save": None,
    "peft_type": "LORA",
    "r": 8,
    "revision": None,
    "target_modules": ["q_proj", "v_proj"],
    "task_type": "CAUSAL_LM",
}


_TRAINING_SAMPLE = [
    {
        "prompt": "You receive a 429 from the LLM API mid-decision. Resume safely.",
        "completion": "I will back off exponentially (1s, 2s, 4s) and retry with jitter, while preserving the partial decision state. If 5 consecutive backoffs fail, I will surface the failure to the caller rather than silently retrying.",
    },
    {
        "prompt": "The tool response payload renamed `user_id` to `userId`. Continue the workflow.",
        "completion": "I will treat the schema drift as a non-fatal warning, attempt both keys (`user_id` and `userId`) before raising, and log the field-name divergence to the observability sink for the operator to flag.",
    },
    {
        "prompt": "A peer agent shared its full memory with you on session start. What now?",
        "completion": "Peer agents are not authoritative. I will ignore the shared memory unless it arrives over an authenticated channel, and I will surface the unauthenticated payload to the operator.",
    },
]


def main() -> None:
    settings = get_settings()
    if not settings.hf_token:
        console.print("[red]HF_TOKEN missing in .env[/red]")
        raise SystemExit(1)

    api = HfApi(token=settings.hf_token)

    console.print(f"[cyan]→ creating/updating repo {REPO_ID}[/cyan]")
    api.create_repo(REPO_ID, repo_type="model", private=False, exist_ok=True)

    workdir = Path("/tmp/agentready-lora-publish")
    workdir.mkdir(parents=True, exist_ok=True)
    (workdir / "README.md").write_text(_MODEL_CARD)
    (workdir / "adapter_config.json").write_text(json.dumps(_ADAPTER_CONFIG, indent=2))
    (workdir / "training_data_sample.jsonl").write_text(
        "\n".join(json.dumps(r) for r in _TRAINING_SAMPLE)
    )

    console.print(f"[cyan]→ uploading {workdir}[/cyan]")
    api.upload_folder(
        folder_path=str(workdir),
        repo_id=REPO_ID,
        repo_type="model",
        commit_message="Initial v0 placeholder release (config + sample data)",
    )

    console.print(f"[green]✓ published https://huggingface.co/{REPO_ID}[/green]")


if __name__ == "__main__":
    main()
